Enhance: Adapt LLVM to introduce JDK Tier 1 tests via GitHub Actions repository dispatch
Signed-off-by: lfeng14 <luofeng13@huawei.com>

diff --git a/.github/workflows/build-cross-compile.yml b/.github/workflows/build-cross-compile.yml
--- a/.github/workflows/build-cross-compile.yml
+++ b/.github/workflows/build-cross-compile.yml
@@ -106,11 +106,19 @@ jobs:
         run: |
           echo "github workspace: ${GITHUB_WORKSPACE}"
           # set CO_REPO and CO_BRANCH
-          TARGET_REPO=`git log -n 1 | grep "CO_REPO" | sed -E 's/^[[:space:]]*CO_REPO[[:space:]]*:[[:space:]]*(.*)$/\1/'`
-          TARGET_BRANCH=`git log -n 1 | grep "CO_BRANCH" | sed -E 's/^[[:space:]]*CO_BRANCH[[:space:]]*:[[:space:]]*(.*)$/\1/'`
+          EVENT_NAME="${{ github.event_name }}"
 
-          if [ -z "${TARGET_REPO}" ]; then
+          if [ "$EVENT_NAME" = 'pull_request_target' ]; then
+            echo "Triggered by pull_request_target, using defaults."
             TARGET_REPO="https://github.com/jeandle/jeandle-llvm.git"
+            TARGET_BRANCH="main"
+          elif [ "$EVENT_NAME" = 'repository_dispatch' ]; then
+            echo "Triggered by repository_dispatch, using client_payload."
+            TARGET_REPO="https://github.com/${{ github.event.client_payload.target_llvm_repo }}.git"
+            TARGET_BRANCH="${{ github.event.client_payload.target_llvm_ref }}"
+          else
+            echo "Error: Unsupported event type: $EVENT_NAME"
+            exit 1
           fi
           echo "target repo of llvm: $TARGET_REPO"
 
@@ -182,11 +190,19 @@ jobs:
         run: |
           echo "github workspace: ${GITHUB_WORKSPACE}"
           # set CO_REPO and CO_BRANCH
-          TARGET_REPO=`git log -n 1 | grep "CO_REPO" | sed -E 's/^[[:space:]]*CO_REPO[[:space:]]*:[[:space:]]*(.*)$/\1/'`
-          TARGET_BRANCH=`git log -n 1 | grep "CO_BRANCH" | sed -E 's/^[[:space:]]*CO_BRANCH[[:space:]]*:[[:space:]]*(.*)$/\1/'`
+          EVENT_NAME="${{ github.event_name }}"
 
-          if [ -z "${TARGET_REPO}" ]; then
+          if [ "$EVENT_NAME" = 'pull_request_target' ]; then
+            echo "Triggered by pull_request_target, using defaults."
             TARGET_REPO="https://github.com/jeandle/jeandle-llvm.git"
+            TARGET_BRANCH="main"
+          elif [ "$EVENT_NAME" = 'repository_dispatch' ]; then
+            echo "Triggered by repository_dispatch, using client_payload."
+            TARGET_REPO="https://github.com/${{ github.event.client_payload.target_llvm_repo }}.git"
+            TARGET_BRANCH="${{ github.event.client_payload.target_llvm_ref }}"
+          else
+            echo "Error: Unsupported event type: $EVENT_NAME"
+            exit 1
           fi
           echo "target repo of llvm: $TARGET_REPO"
 
